apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: localhost:5000/skaioskit/gateway-service:latest
        imagePullPolicy: Always
        command: 
        - /gateway
        - serve
        ports:
        - containerPort: 80
        env:
        - name: BUILD_DATETIME
          value: "${DATETIME}"
---
kind: Service
apiVersion: v1
metadata:
  name: gateway-service-lb
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
  - port: 80
    targetPort: 80
---
